# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/BE_Project/Project/Project_files/CB4CLED/CB4CLED_Top/CB4CLED_Top/vhdl/xilinxprj/CB4CLED_Top.srcs/sources_1/bd/cb4cled_design/ip/cb4cled_design_xbar_1/cb4cled_design_xbar_1.xci
# IP: The module: 'cb4cled_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BE_Project/Project/Project_files/CB4CLED/CB4CLED_Top/CB4CLED_Top/vhdl/xilinxprj/CB4CLED_Top.srcs/sources_1/bd/cb4cled_design/ip/cb4cled_design_xbar_1/cb4cled_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cb4cled_design_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/BE_Project/Project/Project_files/CB4CLED/CB4CLED_Top/CB4CLED_Top/vhdl/xilinxprj/CB4CLED_Top.srcs/sources_1/bd/cb4cled_design/ip/cb4cled_design_xbar_1/cb4cled_design_xbar_1.xci
# IP: The module: 'cb4cled_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BE_Project/Project/Project_files/CB4CLED/CB4CLED_Top/CB4CLED_Top/vhdl/xilinxprj/CB4CLED_Top.srcs/sources_1/bd/cb4cled_design/ip/cb4cled_design_xbar_1/cb4cled_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cb4cled_design_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
